export * from './loadingOutlined'
export * from './homeOutlined'
export * from './settingFilled'
export * from './smileOutlined'
export * from './syncOutlined'
export * from './editOutlined'
export * from './EllipsisOutlined'
export * from './settingOutlined'
